### ISSUE TITLE
Fix test config

### ISSUE THREAD

**Issue by nicholasjhenry** [hollar/web_purifex#2]
https://github.com/hollar/web_purifex/commit/bfb849f9af11cbf22d49ccb11e7fce8bfdfc1ae0#commitcomment-27346103

**Comment by nicocharlery** [comment]
Was fixed on master https://github.com/hollar/web_purifex/commit/6dfce8a02fce502bd77101d4077243d162120d7e

**Comment by nicholasjhenry** [comment]
Ah, perfect. Thank you.
